In [1]:
# question_1
import numpy as np
new_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("the np.array is : ", new_array)
new_list = new_array.tolist()
print("the list is :", new_list)

the np.array is :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
the list is : [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [3]:
# question_2
arr = np.array([[0, 2, 4], [6, 8, 10], [12, 14, 16]])
print("the np.array is : \n", arr)
sum = int(0)
for i in range(0, int(arr.shape[0])):
    sum = sum + arr[i, i]
print("the sum of the diagonal of the array using for loop is  : ", sum)           # first method
arr_1 = np.diag(arr)     # diag function specified in numpy
sum_1 = np.sum(arr_1)    # sum  function specified in numpy
print("the sum of the diagonal of the array using diag and sum  is  : ", sum_1)         # second method
sum_2 = np.trace(arr)
print("the sum of the diagonal of the array  using trace is  : ", sum_2)         # third method


the np.array is : 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
the sum of the diagonal of the array using for loop is  :  24
the sum of the diagonal of the array using diag and sum  is  :  24
the sum of the diagonal of the array  using trace is  :  24


In [5]:
# question_3
my_array = np.array([[1, 2], [3, 5]])
print(my_array)
x = int(2)
for j in np.nditer(my_array):
    if j > x:
        print("%d is higher than 2 " %j)
print("array of numbers higher than 2 ", my_array[my_array>2])   # second method

[[1 2]
 [3 5]]
3 is higher than 2 
5 is higher than 2 
array of numbers higher than 2  [3 5]


In [12]:
#question_4
a = np.array([[0, 2, 4], [6, 8, 10], [12, 14, 16]])
print("the first array : \n", a)
b = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
print("the second array :\n", b)
c = a+b
print("the sum of the two arrays is \n", c)


the first array : 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
the second array :
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
the sum of the two arrays is 
 [[ 1  5  9]
 [13 17 21]
 [25 29 33]]


In [20]:
my_arr = np.array([[3, 3, 3], [4, 5, 6], [7, 8, 9]])
print("the original array :\n ", my_arr)
for k in my_arr:
    print("the mean of each row : ", k.mean())
    print(k-k.mean())


the original array :
  [[3 3 3]
 [4 5 6]
 [7 8 9]]
the mean of each row :  3.0
[0. 0. 0.]
the mean of each row :  5.0
[-1.  0.  1.]
the mean of each row :  8.0
[-1.  0.  1.]
